version: "3.8"

services:
      
  db:
    image: db
    container_name: db
    build:
      context: ./db
      target: db

    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=filesdb
    ports:
      - 5432:5432

    networks:
      - backend

  filesmanagment:
    image: filesmanagment
    container_name: filesmanagment 
    build: ./filesmanagment
    
    ports:
      - "2023:2023"
    depends_on:
      - db

    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 1
        window: 120s
        
    environment:
      DB_URL: "jdbc:postgresql://db:5432/filesdb"
      
    networks:
      - backend
      
networks:
  backend:

volumes:
  postgres-data: